version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container_loadbalancer
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
