version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container2
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./nginx2/nginx.conf:/etc/nginx/nginx.conf
